export interface Recipe {
  id: string;
  title: string;
  category: string;
  difficulty: 'Fácil' | 'Medio' | 'Difícil';
  time: string;
  servings: string;
  description: string;
  ingredients: string[];
  instructions: string[];
  notes?: string;
  image?: string;
  isPremium?: boolean; // Recetas exclusivas que requieren login
}

export const recipes: Recipe[] = [
  // COMIDA CRIOLLA
  {
    id: 'chimichurri-criollo',
    title: 'Chimichurri Criollo Boricua',
    category: 'Comida Criolla',
    difficulty: 'Fácil',
    time: '15 min',
    servings: '4',
    description: 'Salsa tradicional puertorriqueña perfecta para acompañar carnes y vegetales.',
    image: 'https://images.unsplash.com/photo-1596040694312-923e2650fdd2?w=800&q=80',
    ingredients: [
      '1 mazo de perejil',
      '1 mazo de cilantrillo',
      '1 cebolla',
      '1 pimiento rojo',
      '1 pimiento verde',
      '1 pimiento amarillo',
      '1 cabeza de ajo',
      '4 cucharaditas de vinagre de vino',
      'Aceite de oliva',
      'Sal y pimienta a gusto',
    ],
    instructions: [
      'Picar todos los vegetales finamente',
      'Mezclar en un recipiente',
      'Agregar vinagre y aceite de oliva',
      'Dejar reposar por lo menos 4 horas; preferiblemente 24 horas',
    ],
    notes: 'Mejor si se prepara con anticipación para que los sabores se mezclen bien.',
  },
  {
    id: 'ensalada-coditos',
    title: 'Ensalada de Coditos',
    category: 'Comida Criolla',
    difficulty: 'Fácil',
    time: '30 min',
    servings: '6',
    description: 'Ensalada fresca y deliciosa con pasta, vegetales y aderezo cremoso.',
    ingredients: [
      '8 onzas de coditos',
      '5 onzas de guisantes verdes congelados',
      '1 zanahoria',
      '1 cebolla lila',
      '1 pimiento morrón rojo',
      '1 ramita de celery',
      '4 onzas de relish',
      '6 onzas de yogurt griego sin sabor',
      '6 onzas de mayonesa',
      '1 cucharada de mostaza',
      '1 cucharada de azúcar',
      '1 cucharadita de ajo en polvo',
      '2 cucharadas de vinagre de manzana',
      '1 cucharadita de sal',
      '1/2 cucharadita de pimienta negra',
    ],
    instructions: [
      'Hervir coditos y guisantes en agua con sal',
      'Rallar zanahoria y cortar cebolla, pimiento y celery',
      'Colar la pasta y enfriar brevemente con agua fría',
      'Mezclar yogurt, mayonesa, mostaza, azúcar, ajo en polvo, vinagre, sal y pimienta',
      'Integrar pasta, vegetales y relish',
      'Refrigerar antes de servir',
    ],
  },
  {
    id: 'arroz-gandules-costillas',
    title: 'Arroz con Gandules y Costillas de Cerdo',
    category: 'Comida Criolla',
    difficulty: 'Medio',
    time: '90 min',
    servings: '8',
    description: 'Plato tradicional puertorriqueño con arroz, gandules y costillas tiernas.',
    isPremium: true,
    ingredients: [
      '3 tazas de arroz grano largo parboiled',
      '2 latas de gandules sin el agua',
      '2 lbs de costillas de cerdo',
      '1/2 lb de cebolla y pimiento verde',
      '3 sobres de sazón con achiote',
      '2 cubitos de pollo',
      '2 cucharadas de sofrito',
      'Recao/culantro',
      'Aceitunas',
      'Cilantrillo',
      'Sal a gusto',
      '6 tazas de caldo',
    ],
    instructions: [
      'Condimentar costillas con sal y pimienta',
      'Hervir costillas en agua con cebolla, recao, sofrito y cubitos de pollo',
      'Dorar costillas en manteca de cerdo',
      'Añadir cebolla, pimiento, sal, pimientos morrones y aceitunas',
      'Añadir sazón y gandules',
      'Añadir cilantrillo y recao',
      'Incorporar arroz',
      'Añadir el caldo de cocción',
      'Rectificar sal',
      'Cocinar hasta evaporar líquido',
      'Remover con tenedor',
      'Tapar con hojas de plátano y cocinar más',
      'Decorar y servir',
    ],
  },
  {
    id: 'pechuga-pavo-rellena',
    title: 'Pechuga de Pavo Rellena',
    category: 'Comida Criolla',
    difficulty: 'Medio',
    time: '90 min',
    servings: '6',
    description: 'Pechuga de pavo rellena de prosciutto, pimientos y queso manchego. Una alternativa saludable y elegante.',
    isPremium: true,
    ingredients: [
      '2 pechugas de pavo de aproximadamente 1.5 lbs cada una',
      'Prosciutto en lascas',
      'Pimientos de colores cortados en tiras',
      'Cebolla en juliana',
      'Queso manchego',
      'Cúrcuma',
      'Mantequilla clarificada',
      '5 hojas de salvia bien pequeñas',
      'Sal y pimienta',
    ],
    instructions: [
      'Abrir la pechuga estilo mariposa y estirarla',
      'Bañar con mantequilla clarificada y salvia',
      'Condimentar con sal y pimienta',
      'Colocar prosciutto, pimientos, cebolla y queso manchego',
      'Enrollar y añadir cúrcuma para color',
      'Dar otro baño de mantequilla clarificada con salvia',
      'Envolver en papel de aluminio',
      'Hornear a 350F por 30 minutos',
      'Reposar 20 minutos antes de cortar',
      'Servir con acompañamiento',
    ],
  },
  {
    id: 'pavo-horneado',
    title: 'Pavo Horneado',
    category: 'Comida Criolla',
    difficulty: 'Medio',
    time: '180 min',
    servings: '12',
    description: 'Este pavo queda bello. Sirva con arroz con gandules, morcilla, pasteles con lo que quieras. Y si te sobra, al otro día te preparas un sándwich de pavo. ¡Esto es Bello!',
    isPremium: true,
    ingredients: [
      '1 pavo entero',
      'Sal y pimienta',
      'Mantequilla',
      'Hierbas aromáticas',
    ],
    instructions: [
      'Precalentar horno a 325F',
      'Limpiar y secar el pavo',
      'Condimentar por dentro y por fuera',
      'Colocar en bandeja de horno',
      'Hornear según el peso del pavo',
      'Regar con sus jugos cada 30 minutos',
      'Reposar 20 minutos antes de cortar',
    ],
  },
  {
    id: 'lomo-cerdo-relleno',
    title: 'Lomo de Cerdo Relleno de Arroz Mamposteao',
    category: 'Comida Criolla',
    difficulty: 'Medio',
    isPremium: true,
    time: '90 min',
    servings: '8',
    description: 'Lomo de cerdo relleno de arroz mamposteao, plátanos y recao. Un plato elegante y delicioso.',
    ingredients: [
      'Una pieza de lomo de 5 libras',
      '3 cucharadas de sal',
      '1 cucharada de pimienta',
      'Orégano fresco a gusto',
      '3 dientes de ajo',
      'Aceite de oliva',
      'Plátano maduro',
      'Arroz mamposteao',
      'Recao',
    ],
    instructions: [
      'Abrir el lomo estilo mariposa',
      'Golpear para estirarlo',
      'Mezclar orégano, sal, pimienta, ajo y aceite',
      'Condimentar el lomo por ambas partes',
      'Distribuir arroz mamposteao y recao',
      'Freír plátanos maduros y colocarlos encima',
      'Enrollar y amarrar',
      'Hornear a 375F por 40 min',
      'Luego 10 min en broil',
      'Reposar antes de servir',
    ],
  },
  {
    id: 'pollo-guisado',
    title: 'Pollo Guisado',
    category: 'Comida Criolla',
    isPremium: true,
    difficulty: 'Medio',
    time: '60 min',
    servings: '6',
    description: 'Pollo guisado con papas, zanahorias y vegetales. Un clásico puertorriqueño reconfortante.',
    ingredients: [
      '1 pollo entero cortado en piezas',
      '3 o 4 papas',
      '3 o 4 zanahorias',
      '5 ajíes dulces',
      'Cilantrillo',
      'Recao (culantro)',
      'Orégano',
      '1 cebolla y pimientos de colores',
      '4 onz de salsa de tomate',
      'Sal kosher',
      'Ajo en polvo',
      'Cebolla en polvo',
      'Azúcar negra',
      'Paprika',
      'Pimienta negra',
    ],
    instructions: [
      'Condimentar el pollo',
      'Dorar en aceite caliente',
      'Retirar y reservar',
      'Saltear cebolla, pimientos y ajo',
      'Agregar salsa de tomate',
      'Retornar el pollo',
      'Agregar papas y zanahorias',
      'Cocinar a fuego medio hasta que esté tierno',
      'Agregar cilantrillo y recao',
      'Servir caliente',
    ],
  },

  // AIR FRYER
  {
    id: 'hamburger-air-fryer',
    title: 'Hamburger en Air Fryer',
    isPremium: true,
    category: 'Air Fryer',
    difficulty: 'Fácil',
    time: '20 min',
    servings: '4',
    description: 'Hamburguesas jugosas preparadas en freidora de aire con relleno de tuétano y bacon.',
    ingredients: [
      'Carne molida de res',
      'Bacon',
      'Cebolla',
      'Tuétano',
      'Sal',
      'Pimienta',
      'Mantequilla',
      'Mayonesa',
      'Queso',
    ],
    instructions: [
      'Dorar bacon en cubitos',
      'Caramelizar cebolla en esos jugos',
      'Cocinar tuétano 10 min a 400F',
      'Integrarlo con cebolla y bacon',
      'Formar hamburger y rellenarlo',
      'Cocinar 8 min a 400F',
      'Añadir queso y cocinar un poco más',
      'Montarlo en pan',
    ],
  },
  {
    id: 'pollo-entero-air-fryer',
    title: 'Pollo Entero en Air Fryer',
    isPremium: true,
    category: 'Air Fryer',
    difficulty: 'Medio',
    time: '90 min',
    servings: '4',
    description: 'Pollo entero crujiente y jugoso preparado en air fryer con hierbas aromáticas.',
    ingredients: [
      '1 pollo entero',
      'Sazonador',
      '2 cucharadas tomillo',
      '2 cucharadas de sofrito',
      '1/2 mazo de cilantrillo',
      'Aceite de oliva',
      'Sal y pimienta',
    ],
    instructions: [
      'Mezclar ingredientes',
      'Despegar la piel del pollo con cuidado',
      'Adobar con la mezcla',
      'Amarrar muslos',
      'Cocinar 390F por 13 min pechuga arriba',
      'Virar y cocinar 12 min más',
      'Bajar a 265F y dejar 49 min',
      'Reposar 15 min',
    ],
  },
  {
    id: 'steak-air-fryer',
    title: 'Steak en 15 Minutos',
    category: 'Air Fryer',
    difficulty: 'Fácil',
    time: '20 min',
    servings: '2',
    description: 'Steak jugoso y delicioso preparado en air fryer en solo 15 minutos de cocción.',
    isPremium: true,
    ingredients: [
      '2 steak (NY steak, ribeye o el que prefieras)',
      '4 dientes de ajo',
      'Aceite',
      'Mantequilla',
      'Romero',
      'Sal y pimienta',
    ],
    instructions: [
      'Condimentar carne',
      'Añadir aceite en la caja del air fryer y colocar carne',
      'Añadir ajo, mantequilla, romero y más aceite',
      'Cocinar 10 min a 400F para término medium',
      'Reposar 5 a 10 min',
      'Cortar y servir',
    ],
  },
  {
    id: 'pork-belly-air-fryer',
    title: 'Pork Belly en Air Fryer',
    isPremium: true,
    category: 'Air Fryer',
    difficulty: 'Medio',
    time: '75 min',
    servings: '6',
    description: 'Pork belly crujiente por fuera y tierno por dentro, preparado en air fryer.',
    ingredients: [
      'Pork belly de 3 lbs aproximadamente',
      'Sal kosher',
      'Ajo en polvo',
      'Cebolla en polvo',
      'Orégano',
      'Azúcar negra',
      'Paprika',
      'Pimienta negra',
      'Aceite de oliva',
      'Vinagre blanco',
    ],
    instructions: [
      'Hacer cortes del lado de la carne',
      'Condimentar',
      'Formar "casita" con papel de aluminio',
      'Untar cuero con vinagre blanco y sal abundante',
      'Cocinar 350F por 45 min',
      'Untar con sus jugos',
      'Subir a 385F por 15 min',
      'Sacar, reposar 10 min',
      'Cortar y servir',
    ],
  },
];
