/**
 * Contenido del recetario PDF.
 * Cursor actualiza este archivo cuando el usuario dicta o edita recetas.
 * Luego: `node scripts/generate-recetario.js` o `npm run generate:recetario`
 */

module.exports = {
  titulo: 'Las 20 Recetas Favoritas Del Sabor',
  subtitulo: 'Recetas boricuas con sazón de verdad',
  autor: 'El Gordito del Sabor',
  sitio: 'https://gorditodelsabor.com',
  instagram: '@elgorditodelsaborpr',
  instagramUrl: 'https://www.instagram.com/elgorditodelsaborpr',

  bienvenida: {
    titulo: 'Bienvenido a la mesa de El Gordito del Sabor',
    texto: [
      'Este libro nace de una pasión real por la cocina, por Puerto Rico y por esos momentos que se crean cuando la comida reúne a la gente correcta alrededor de una mesa. El Gordito del Sabor representa esa esencia tan nuestra de demostrar cariño a través de un buen plato, de cocinar con intención y de compartir con el corazón.',
      'Aquí no vas a encontrar recetas complicadas ni una cocina lejana. Vas a encontrar sabor, tradición, ideas prácticas y ese estilo sencillo que hace sentir que cocinar sí es posible. Porque si algo cree El Gordito, es que la comida no solo alimenta: también conecta, consuela, une y crea recuerdos.',
      'Cada una de estas recetas lleva un pedazo de historia, de familia y de cultura boricua. Mi deseo es que este libro no solo te inspire a cocinar, sino también a disfrutar el proceso, a inventar, a compartir y a querer a los tuyos a través de lo que prepares.',
      'Gracias por abrirme un espacio en tu cocina, en tu mesa y en tu hogar. Vamos a meterle sabor. Esto es bello.',
    ].join('\n\n'),
  },

  historias: [
    {
      id: 'h1',
      titulo: 'El Gordito del Sabor no es solo un nombre',
      texto: [
        'El Gordito del Sabor no nació para complicar la cocina ni para hacer sentir a nadie que cocinar es solo para expertos. Nació desde algo mucho más sencillo y mucho más poderoso: el deseo de compartir. Detrás de este nombre hay un apasionado de la cocina puertorriqueña, alguien que aprendió que una receta bien hecha puede decir mucho sin hablar demasiado.',
        'El Gordito representa a esa persona que existe en tantas familias boricuas: la que siempre está dispuesta a cocinar, a servir, a reunir y a demostrar cariño a través de la comida. No es solo un personaje. Es una forma de querer. Es ese hermano, primo, tío o pana que sabe que muchas veces el amor se demuestra poniendo un plato en la mesa.',
        'Por eso este libro no está hecho solo para que sigas pasos. Está hecho para que sientas que tú también puedes cocinar, compartir y crear momentos que la gente recuerde. Porque si algo cree El Gordito del Sabor, es que cuando la comida se hace con amor, siempre sabe mejor.',
      ].join('\n\n'),
    },
    {
      id: 'h2',
      titulo: 'En muchas casas, el amor se servía en un plato',
      texto: [
        'Hay recuerdos que uno no olvida. No porque fueran lujosos, sino porque estaban llenos de verdad. El Gordito recuerda que, aun en medio de dificultades económicas, en la casa de sus padres siempre aparecía un plato de comida deliciosa para quien llegara. No había excesos. No había de más. Pero sí había algo que nunca faltaba: la intención de compartir.',
        'Esa es una de las raíces más profundas de esta marca. La idea de que no hace falta tener mucho para dar algo valioso. A veces basta con una mesa, una olla caliente y las ganas de hacer sentir bien a alguien. En Puerto Rico, eso se entiende sin tener que explicarlo demasiado. Porque muchos crecimos viendo cómo la comida resolvía, unía y abrazaba.',
        'Quizás por eso las recetas del Gordito se sienten tan cercanas. Porque no salen desde la apariencia. Salen desde la memoria. Desde una cocina real. Desde un hogar donde el sabor no dependía del lujo, sino del corazón con que se cocinaba.',
      ].join('\n\n'),
    },
    {
      id: 'h3',
      titulo: 'Los códigos de la cocina se aprenden en casa',
      texto: [
        'El Gordito aprendió a cocinar como aprenden muchos puertorriqueños: viendo, ayudando, preguntando y probando. Su base vino de sus padres y de sus hermanos, especialmente del mayor. Ahí fue donde comenzó todo. Ahí fue donde aprendió los códigos de la comida, esos que no siempre se enseñan con medidas exactas, pero sí con costumbre, observación y cariño.',
        'Después vino el aprendizaje autodidacta, la curiosidad y las ganas de seguir creciendo. Pero la raíz siempre fue la misma: la familia. Porque en nuestra cultura, la cocina no es solo una habilidad. También es herencia. Es identidad. Es una forma de mantener vivas las tradiciones que pasan de generación en generación.',
        'Cada receta que encuentras aquí tiene algo de eso. Tiene algo del hogar, de la mesa compartida, de la enseñanza sencilla y del orgullo de saber que nuestros sabores cuentan quiénes somos. Y cuando una receta lleva eso adentro, deja de ser solo comida. Se convierte en historia.',
      ].join('\n\n'),
    },
    {
      id: 'h4',
      titulo: 'Si yo puedo, tú también',
      texto: [
        'Una de las cosas más importantes para El Gordito del Sabor es que la gente no mire sus recetas desde lejos. Él no quiere que las vean y piensen “eso se ve brutal, pero yo no puedo hacerlo”. Al contrario. Quiere que cada persona sienta que sí puede intentarlo, aprender y hasta hacerlo a su manera.',
        'Para él, cocinar nunca ha sido un acto de perfección. Ha sido un acto de amor. Una forma de dar. Una manera de decir “te pensé”, “te quise”, “te preparé esto con cariño”. Por eso su cocina es sencilla, práctica y sin complicaciones innecesarias. Porque lo importante no es impresionar. Lo importante es compartir.',
        'Si este libro logra que alguien pierda el miedo a cocinar, se anime a preparar una receta para su familia o descubra que tiene más sazón del que pensaba, entonces ya cumplió su propósito. Porque cuando uno cocina desde el corazón, siempre deja algo bueno en la mesa.',
      ].join('\n\n'),
    },
    {
      id: 'h5',
      titulo: 'Puerto Rico vive en cada bocado',
      texto: [
        'Puerto Rico no es un detalle dentro de la marca del Gordito. Es el centro. Es la raíz. Es la inspiración que le da sentido a todo. La cocina puertorriqueña, con su mezcla de influencias españolas, africanas y nativas, forma parte de una herencia rica, amplia y profundamente nuestra.',
        'El sabor boricua no está solo en los ingredientes. Está en la manera de cocinar. En cómo se sirve. En cómo se insiste en que comas un poco más. En cómo se convierte cualquier comida en una experiencia de familia, conversación y encuentro. Esa forma tan nuestra de vivir la comida es parte esencial de lo que El Gordito del Sabor quiere representar.',
        'Este libro también es una manera de honrar eso. De recordar que nuestras recetas no son cualquier cosa. Son cultura. Son memoria. Son orgullo. Y mientras sigamos cocinándolas, compartiéndolas y enseñándolas, una parte hermosa de Puerto Rico seguirá viva en cada mesa.',
      ].join('\n\n'),
    },
  ],

  cierre: {
    titulo: 'Gracias por hacerle un espacio al Gordito en tu mesa',
    texto: [
      'De todas las cosas bonitas que puede traer este proyecto, hay una que El Gordito del Sabor nunca da por sentada: el privilegio de entrar, aunque sea un poquito, en los hogares de tanta gente. Poder estar presente en la mesa de otros, acompañar momentos en familia y formar parte de recuerdos nuevos es algo profundamente especial.',
      'Por eso este libro también nace desde el agradecimiento. Gracias por abrirle espacio a estas recetas, por permitir que esta cocina llegue a tu casa y por seguir dándole vida a todo lo que representa esta marca. Si algo desea El Gordito, es que cada plato que prepares aquí te recuerde que cocinar sigue siendo una de las maneras más lindas de demostrar amor.',
      'Si llegaste hasta aquí, gracias de corazón. Si estas páginas te dieron ganas de cocinar, compartir y querer a los tuyos un poco más, entonces esto es bello.',
    ].join('\n\n'),
  },

  recetas: [
    {
      nombre: 'Salmuera',
      imagen: 'public/Imagenes20recetas/Salmuera.jpeg',
      intro: 'Antes de tirarte a la parrilla, esto es lo que le da sabor de verdad y ayuda a que la carne no salga seca. La guardas en la nevera y la usas cuando toque. Eso es bello.',
      tiempo: '25 min activo + mín. 4 h reposo',
      porciones: 'N/A (líquido para marinar)',
      dificultad: 'Fácil',
      ingredientes: [
        '1 litro de agua caliente',
        '3.5 onzas de sal parrillera o gruesa',
        '10–15 granos de pimienta negra',
        '2 cucharaditas de chili flakes',
        '5–7 dientes de ajo',
        '3 a 4 ramas de orégano fresco',
        '6 a 7 ramas de tomillo fresco',
        '3 a 4 ramas grandes de romero fresco',
        '4 hojas de laurel',
        '1 cucharada de paprika',
      ],
      instrucciones: [
        'Calienta el agua con la sal. No debe hervir: solo calentar hasta que se disuelva la sal.',
        'En un envase, preferiblemente de cristal, coloca el resto de los ingredientes.',
        'Vierte poco a poco el agua caliente sobre los ingredientes.',
        'Agita la mezcla muy bien para integrar.',
        'Déjala descansar al menos 4 horas antes de usarla.',
        'En nevera te dura unas 2 semanas aproximadamente.',
      ],
      notas: 'Esta salmuera condimenta, aporta sabor y humedad para que la carne quede blandita. Dura ~2 semanas refrigerada. ¡Esto es bello!',
    },
    {
      nombre: 'Hamburger de Churrasco a mi Estilo',
      imagen: 'public/Imagenes20recetas/Hamburger de Churrasco.jpeg',
      intro: 'Churrasco molido no tiene que ser caro para saber a gloria. La salsa con miel y tocineta crujiente lo sube a otro nivel. Una copa de vino y pa\'lante.',
      tiempo: '35–45 min',
      porciones: '~4 hamburguesas',
      dificultad: 'Media',
      ingredientes: [
        '2 lbs de churrasco molido',
        'Queso de tu preferencia',
        'Sal kosher',
        'Pimienta',
        '— Para la salsa —',
        '2 cucharadas de mayonesa',
        '1 cucharada de ketchup',
        '1 cucharada de miel',
        'Tocineta bien crujiente, cortada en pedacitos pequeños',
      ],
      instrucciones: [
        'Pídele al carnicero que te muela dos libras de churrasco (o muelas el churrasco en casa).',
        'Dale forma a las hamburguesas y condiméntalas con sal kosher y pimienta.',
        'Corta tiras de churrasco en cubitos pequeños y cocínalos en un sartén hasta que doren; retira del sartén.',
        'En el mismo sartén, con la grasa del bacon, cocina las hamburguesas al término que más te guste.',
        'Añade tu queso favorito y, cuando derrita, retira del fuego.',
        'Tuesta el pan en el mismo sartén para que absorba el sabor.',
        'En un envase: mayonesa, ketchup y miel; mezcla bien. Incorpora el bacon picado.',
        'En la tapa inferior del pan: un poco de salsa, la hamburguesa, más salsa y la tapa superior.',
        'Acompaña con lo que quieras; en el video: batatas dulces fritas con parmesano y aceite de trufa.',
      ],
      notas: 'El sabor sorprende aunque el churrasco sea económico. Acompaña con una buena copa de vino. ¡Eso es bello!',
    },
    {
      nombre: 'Biftec Encebollado a mi Estilo',
      imagen: 'public/Imagenes20recetas/Biftec Encebollado a Mi Estilo.jpeg',
      intro: 'Esto es marinar con cabeza: cebolla, emulsión de aceite y vinagre, y fuego bajo hasta que el bistec se ponga tierno. Con arroz y habichuelas queda de película.',
      tiempo: '~30 min prep. + 4 h macerado + ~1 h cocción',
      porciones: '8–10',
      dificultad: 'Media',
      ingredientes: [
        '4 lbs de bistec (lomillo o filete)',
        '3 a 4 cebollas grandes en rodajas',
        '2 tazas de aceite de oliva',
        '1 taza de vinagre blanco',
        'Sal y pimienta a gusto',
        'Orégano',
        '3 a 4 dientes de ajo',
      ],
      instrucciones: [
        'Pela las cebollas y córtalas en rodajas.',
        'Coloca los bistecs entre dos hojas de film y dale golpes con pilón o maceta para ablandarlos.',
        'Condimenta con sal y pimienta a gusto.',
        'Arma capas: cebolla, bistec, cebolla… hasta que la última capa sea cebolla.',
        'En otro envase, bate aceite de oliva y vinagre blanco hasta formar una emulsión.',
        'Vierte esa mezcla sobre el bistec y las cebollas.',
        'Macera en nevera 4 horas.',
        'Saca el bistec media hora antes de cocinar para que baje el frío.',
        'En sartén bien caliente, sella los bistecs por ambos lados.',
        'Vierte la cebolla y toda la mezcla de aceite y vinagre.',
        'Ralla los dientes de ajo encima.',
        'Tapa y cocina a fuego medio-bajo o bajo ~1 hora.',
      ],
      notas: 'Yo lo prefiero con arroz blanco, habichuelas y tostones, pero va con casi todo. ¡Esto es bello!',
    },
    {
      nombre: 'Arroz Chino',
      imagen: 'public/Imagenes20recetas/arroz-chino-ai.jpg',
      intro: 'Arroz blanco ya cocido, sésamo, jamón, cerdo ahumado y huevo revuelto. Es rápido, rinde y la casa huele a comida china de verdad.',
      tiempo: '30–40 min',
      porciones: '6–8',
      dificultad: 'Media',
      ingredientes: [
        '2–3 tazas de arroz blanco cocido',
        'Aceite de sésamo',
        '1/2 cebolla grande o 1 mediana',
        '2 cucharadas de ajo picado',
        '8 onzas de jamón de cocinar',
        '1 1/2 lb de carne de cerdo ahumada',
        '4–5 huevos',
        'Vinagre de arroz',
        'Vegetales mixtos (opcional)',
        'Salsa soya',
        'Cebollines',
      ],
      instrucciones: [
        'Sartén caliente: aceite de sésamo, cebolla ~1 min.',
        'Añade el ajo; cocina 1–2 minutos.',
        'Jamón en cubitos; cocina con cebolla y ajo 2–3 minutos.',
        'Añade cerdo ahumado y un toque de vinagre de arroz; ~5 minutos.',
        'Retira todo a un envase aparte.',
        'Más aceite de sésamo en el sartén y bate los huevos.',
        'Añade el arroz blanco cocido; mezcla bien.',
        'Incorpora de nuevo carne ahumada, jamón, cebolla y ajo; integra sabores.',
        'Opcional: vegetales mixtos.',
        'Salsa soya al gusto hasta el color y sabor deseados.',
        'Cebollines picados; mezcla y cocina 2–3 minutos más.',
        'Sirve.',
      ],
      notas: 'Súper fácil y muy rico. Acompaña con tu carne favorita y tostones con ajo. ¡Esto es bello!',
    },
    {
      nombre: 'Pork Belly',
      imagen: 'public/Imagenes20recetas/Pork Belly.jpeg',
      intro: 'Cuadricula la piel, sazona, envuélvelo en aluminio como casita y al air fryer. La carne jugosa y el cuero crocante no fallan. Una cava fría y listo.',
      tiempo: '~50 min (air fryer)',
      porciones: '4–6',
      dificultad: 'Media',
      ingredientes: [
        'Pork belly 2.5–3 lbs aprox.',
        '— Sazonador o alternativa —',
        'Sal kosher',
        'Orégano',
        'Pimienta recién molida',
        'Aceite de oliva (no extra virgen) para el cuero',
        'Papel de aluminio',
      ],
      instrucciones: [
        'Por el lado de la carne, haz cortes para cuadricularla.',
        'Condimenta con el sazonador o sal, pimienta y orégano.',
        'Coloca el lado de la carne sobre papel aluminio y forma una "casita" cerrada.',
        'Air fryer a 400 °F ~40 min (en otros equipos puede tardar más).',
        'A los ~30 min: con brocha, unta el cuero con aceite de oliva (no extra virgen) y sal.',
        'Saca del air fryer, retira del aluminio y reposa 5–10 minutos.',
        'Corta y sirve.',
      ],
      notas: 'La técnica cocina la carne bien y deja el cuero tostado y crocante. Acompaña con una Cava bien fría. ¡Esto es bello!',
    },
    {
      nombre: 'Tostones en Air Fryer',
      imagen: 'public/Imagenes20recetas/tostones-airfryer-ai.jpg',
      intro: 'Mantequilla, aceite, ajo y dos pasadas en el air fryer. Quedan crujientes sin tanto aceite de freidora. El mayo-ketchup con ajo cierra el combo.',
      tiempo: '~25 min',
      porciones: '2–4',
      dificultad: 'Fácil',
      ingredientes: [
        '2 plátanos verdes',
        '1/4 barra de mantequilla',
        '1/4 taza de aceite de oliva',
        '3 dientes de ajo',
        '— Mayo-ketchup —',
        '2 cucharadas de mayonesa',
        'Ketchup a gusto',
        '1 diente de ajo',
      ],
      instrucciones: [
        'Corta y pela el plátano.',
        'Corta en ruedas ~1 pulgada y colócalas en un envase.',
        'Derrite la mantequilla, añade aceite de oliva y ajo rallado; mezcla bien.',
        'Pon las rodajas en la canasta del air fryer y pincela cada una con la mezcla.',
        '380 °F ~10 minutos.',
        'Saca y aplasta como tostones siempre.',
        'Vuelve a la bandeja y pincela otra vez con la mezcla.',
        '380 °F 8–10 minutos más.',
        'Mayo-ketchup: mayonesa, ketchup y ajo rallado; mezcla y sirve al lado.',
      ],
      notas: 'Saludables y bien ricos. ¡Esto es bello!',
    },
    {
      nombre: 'Sazonador para Pollo, Cerdo y Pescado',
      imagen: 'public/Imagenes20recetas/sazonador-ai.jpg',
      intro: 'Un frasco que te saca de todo: pollo, chuleta, pescado. Para carne roja yo sigo con sal y pimienta nada más. Mezclas, guardas y cocinas.',
      tiempo: '10 min',
      porciones: 'Múltiples aplicaciones',
      dificultad: 'Fácil',
      ingredientes: [
        '6 cucharadas de sal kosher',
        '2 cucharadas de ajo en polvo',
        '2 cucharadas de cebolla en polvo',
        '2 cucharadas de orégano',
        '2 cucharadas de cilantrillo seco',
        '2 cucharadas de azúcar negra',
        '2 cucharadas de paprika',
        '1 cucharada de pimienta negra',
      ],
      instrucciones: [
        'Mezcla todos los ingredientes en un envase que selle bien y no le entre aire.',
        'Úsalo en recetas de pollo, cerdo y pescado.',
        'No se recomienda para carne roja: para eso solo sal y pimienta.',
      ],
      notas: 'Guárdalo hermético y dura semanas. Siempre a la mano para cualquier carne.',
    },
    {
      nombre: 'Chimichurri con Ribeye y Tostones',
      imagen: 'public/Imagenes20recetas/chimichurri-ribeye-ai.jpg',
      intro: 'Perejil, cilantro, cebolla, pimientos y mucho aceite de oliva. Lo dejas reposar y después va sobre churrasco, pollo, tostones… lo que sea. Si quieres atajo, cebolla y pimientos congelados picados.',
      tiempo: '40 min activo + mín. 4 h reposo (ideal 24 h)',
      porciones: '~2 tazas de salsa',
      dificultad: 'Fácil',
      ingredientes: [
        '1/2 mazo de perejil',
        '1/2 mazo de cilantrillo',
        '1 cebolla mediana',
        '1/2 pimiento rojo',
        '1/2 pimiento verde',
        '1 cabeza de ajo',
        '2 cucharaditas de vinagre de vino',
        'Abundante aceite de oliva',
        'Sal y pimienta a gusto',
      ],
      instrucciones: [
        'Pica fino el perejil.',
        'Igual con el cilantrillo; a un envase.',
        'Cebolla en cubos pequeños; al envase.',
        'Pimientos rojo y verde en pedazos pequeños; integra.',
        'Ajo pelado y rallado; integra.',
        'Añade las 2 cucharaditas de vinagre de vino.',
        'Un poco de aceite de oliva y mezcla.',
        'Sal y pimienta; mezcla.',
        'Aceite de oliva abundante hasta cubrir; mezcla bien.',
        'Reposa mínimo 4 horas; preferible 24 horas para integrar sabores.',
      ],
      notas: 'Sirve para carnes rojas, cerdo, pollo, tostones, viandas. Puedes usar cebolla y pimientos congelados ya picados. ¡Esto es bello!',
    },
    {
      nombre: 'Guineitos en Escabeche',
      imagen: 'public/Imagenes20recetas/Guineitos en Escabeche.jpeg',
      intro: 'Guineos verdes, montón de cebolla, aceite, vinagre y sabor fuerte. De un día para otro en la nevera y eso pica distinto. Para acompañar cualquier cosa.',
      tiempo: '~1 h 15 min + reposo overnight',
      porciones: 'Tanda grande',
      dificultad: 'Media',
      ingredientes: [
        '28 guineos verdes',
        '3 lbs de cebolla',
        '2 latas de 15 oz de pimiento morrón',
        '3 tazas de aceite de oliva',
        '1 1/2 taza de vinagre blanco',
        '5 hojas de laurel',
        '15 granos de pimienta o pimienta molida',
        '15 dientes de ajo',
        '10 aceitunas rellenas picadas',
      ],
      instrucciones: [
        'Olla con agua abundante y sal; lleva a hervir.',
        'Corta y pela los guineos verdes.',
        'En otra olla: cebolla (en juliana), pimientos morrones, ajo, aceite, vinagre, pimienta, laurel y aceitunas.',
        'Cocina a fuego medio ~35 minutos.',
        'Hierve los guineos ~20 minutos aprox.; saca y deja enfriar.',
        'Corta los guineos y colócalos en un envase.',
        'Integra la salsa escabeche y mezcla bien.',
        'Ideal: refrigera de un día para otro para disfrutar.',
      ],
      notas: 'Para picar o acompañar cualquier plato. El sabor es único. ¡Esto es bello!',
    },
    {
      nombre: 'Ensalada de Coditos',
      imagen: 'public/Imagenes20recetas/Ensalada de Coditos.jpeg',
      intro: 'Mayo, sour cream, miel, mostaza y vegetales bien picaditos. La dejas fría y sale cremosa. Puedes meter zanahoria, guisantes o maíz si te gusta jugar.',
      tiempo: '25 min + mín. 2 h en nevera',
      porciones: '6–8',
      dificultad: 'Fácil',
      ingredientes: [
        '1/2 caja de coditos (gluten free en el video)',
        '1/2 taza de mayonesa',
        '1/2 taza de sour cream',
        '2 cucharaditas de mostaza',
        '2 cucharadas de miel pura',
        '1/2 morrón rojo, 1/2 amarillo, 1/2 naranja',
        '1/2 cebolla morada',
        'Jamón de pavo',
        'Cebollín',
        'Sal y pimienta a gusto',
        'Cilantrillo',
      ],
      instrucciones: [
        'Hierve los coditos según las instrucciones del empaque.',
        'Pica fino pimientos, cebolla y cebollín.',
        'Mezcla mayonesa y sour cream en un envase.',
        'Añade mostaza y miel; integra bien.',
        'En otro envase: coditos cocidos, pimientos, cebolla morada y jamón; mezcla.',
        'Añade cebollín, sal y pimienta.',
        'Vierte todo sobre la mezcla de mayonesa y mezcla con paleta.',
        'Nevera al menos 2 horas antes de servir.',
      ],
      notas: 'Fácil y muy rica. Puedes variar los vegetales: zanahoria rallada, guisantes o maíz. ¡Esto es bello!',
    },
    {
      nombre: 'Lomo de Cerdo Relleno de Arroz Mamposteao',
      imagen: 'public/Imagenes20recetas/Lomo relleno de mamposteado.jpeg',
      intro: 'Abres el lomo mariposa, le metes mamposteao, recao y plátano maduro frito, enrollas, amarras y al horno. Cuando lo cortes, el relleno habla solo.',
      tiempo: '~1 h 30 min (incluye horno y reposo)',
      porciones: '8–10',
      dificultad: 'Alta',
      ingredientes: [
        '1 pieza de lomo ~5 lbs',
        '3 cucharadas de sal',
        '1 cucharada de pimienta',
        'Orégano fresco al gusto',
        '3 dientes de ajo',
        'Aceite de oliva',
        'Plátano maduro (frito)',
        'Arroz mamposteao (preparado)',
        'Recao (culantro)',
        'Hilo de cocinar',
      ],
      instrucciones: [
        'Con cuchillo afilado, abre el lomo estilo mariposa.',
        'Con maceta o rodillo, golpea para estirar bien el lomo.',
        'Mezcla orégano, sal, pimienta, ajo y aceite de oliva.',
        'Condimenta el lomo por ambas caras con esa mezcla.',
        'Distribuye el arroz mamposteao en una cara; añade recao (culantro).',
        'Fríe plátanos maduros y colócalos sobre el arroz.',
        'Enrolla en cilindro y amarra bien, especialmente los extremos.',
        'Horno 375 °F ~40 min + ~10 min broil para dorar.',
        'Reposa 15–20 minutos antes de cortar.',
      ],
      notas: 'Acompaña con ensalada, mofongo, tostones o majado. ¡Esto es bello!',
    },
    {
      nombre: 'Tacada a mi Estilo',
      imagen: 'public/Imagenes20recetas/Tacada a Mi Estilo.jpeg',
      intro: 'Paella o sartén grande: sellas carnes, metes vegetales al centro, tomate, jalapeños y queso al final. Nachos, tacos o derecho del fogón. Tú mandas en las cantidades.',
      tiempo: '~45 min',
      porciones: '10+ (fiesta)',
      dificultad: 'Media',
      ingredientes: [
        '2 lbs de sirloin de cerdo',
        '2 lbs de caderas de pollo',
        '2 lbs de churrasco',
        '2 lbs de chorizos parrillero y embutidos',
        '2 lbs de pimientos de colores y cebolla',
        '1 lb de tomates (diced tomatoes)',
        '2 o 3 jalapeños (al gusto)',
        'Sal y pimienta',
        'Orégano',
        'Sazonador para tacos',
        'Queso al gusto',
        'Aceite de oliva o manteca',
      ],
      instrucciones: [
        'En sartén amplio o paella: aceite o manteca; sella las carnes por separado.',
        'Condimenta a gusto (sal y pimienta bastan).',
        'Acomoda las carnes alrededor y deja hueco al centro para cebolla y pimientos; ~5 min con sazonador para tacos.',
        'Añade tomates (diced); otro poco de sazonador; ~5 min.',
        'Jalapeños (omite si no quieres picante).',
        'Mezcla todo ~10 minutos hasta integrar.',
        'Añade queso de tu preferencia.',
        'Sirve en nachos, tacos, burritos o solo.',
      ],
      notas: 'Puedes variar las carnes y las cantidades. Lo que sí es que está sabrosa. ¡Esto es bello!',
    },
    {
      nombre: 'Hamburger de Tocineta a mi Estilo',
      imagen: 'public/Imagenes20recetas/Hamburger de Tocineta a mi estilo..jpeg',
      intro: 'Chorizo parrillero mezclado con carne molida, envuelto en tocineta en capas y al BBQ: fuego directo primero, indirecto después. No hace falta mucho más condimento.',
      tiempo: '~45 min (incluye BBQ)',
      porciones: '4–6',
      dificultad: 'Media',
      ingredientes: [
        '4–6 tiras de tocineta',
        '1 lb de chorizo parrillero argentino',
        '1 lb de carne molida de res',
      ],
      instrucciones: [
        'Haz un corte fino y desprende la envoltura del chorizo parrillero.',
        'Mezcla el chorizo con la carne molida de res.',
        'Extiende las tiras de tocino superpuestas en un extremo.',
        'Distribuye la mezcla de carne sobre toda la superficie de la tocineta.',
        'Enrolla con firmeza para que quede bien cerrado.',
        'Opcional: palillos de madera para dar más firmeza.',
        'BBQ a fuego directo hasta dorar, vuelta y vuelta unos minutos por cada lado.',
        'Luego fuego indirecto ~15 minutos.',
        'Sirve con pan, papas o ensalada.',
      ],
      notas: 'Esta versión tiene mucho sabor y no necesita condimentos extra. Puedes añadir queso si deseas.',
    },
    {
      nombre: 'Churrasco Enrollado Relleno',
      imagen: 'public/Imagenes20recetas/Churrasco Relleno Enrollad.jpeg',
      intro: 'Aplastas el churrasco, le metes jamón serrano o prosciutto, queso, enrollas y al grill. Pocos ingredientes, plato que sirve de picadera o principal. Vino tinto no pelea.',
      tiempo: '~45 min + 10 min reposo',
      porciones: '4 medallones',
      dificultad: 'Media–Alta',
      ingredientes: [
        'Churrasco (cantidad al gusto)',
        'Sal y pimienta',
        'Jamón serrano o prosciutto (o bacon)',
        'Queso provolone y cheddar',
      ],
      instrucciones: [
        'Golpea el churrasco entre dos films para expandirlo.',
        'Coloca capas de prosciutto, jamón o bacon y queso al gusto.',
        'Enrolla firmemente y amarra con hilo de cocina o pinchos.',
        'Corta en ~4 piezas cilíndricas; condimenta con sal y pimienta.',
        'A la parrilla ~375 °F hasta que se despegue solo; voltea.',
        'Al punto deseado, retira y reposa 10 minutos antes de cortar.',
      ],
      notas: 'Divino con pocos ingredientes. Sirve como picadera o plato principal. Una copa de vino tinto cae bien. ¡Esto es bello!',
    },
    {
      nombre: 'Hamburger en Plantilla de Pastelillo',
      imagen: 'public/Imagenes20recetas/Hamburger Envuelto en Plantilla de Pastelillos.jpeg',
      intro: 'Carne, queso, bacon y masa de pastelillo: es croqueta gigante con alma de burger. Cuatro ingredientes sencillos, resultado que no se olvida.',
      tiempo: '~35 min',
      porciones: '4',
      dificultad: 'Media',
      ingredientes: [
        '1 lb de carne de res',
        'Sal y pimienta a gusto',
        'Queso americano y suizo',
        'Mayonesa',
        'Bacon',
        '1 huevo batido',
        '4 plantillas de pastelillos',
      ],
      instrucciones: [
        'Condimenta la carne de res con sal y pimienta; forma 4 tortitas del tamaño de la plantilla.',
        'Cocina el bacon hasta crujiente; reserva.',
        'Cocina las tortitas de carne al punto deseado; añade queso encima y deja derretir.',
        'Sobre una plantilla: mayonesa, tortita con queso, bacon.',
        'Cubre con la segunda plantilla y sella los bordes presionando con un tenedor.',
        'Pincela con huevo batido por ambos lados.',
        'Cocina en sartén a fuego medio o en air fryer a 375 °F ~8–10 min, volteando a mitad.',
        'Sirve caliente.',
      ],
      notas: 'La masa de pastelillo queda crujiente por fuera y el queso derretido por dentro. Un hit asegurado.',
    },
    {
      nombre: 'Pernil al Caldero al Estilo Boricua',
      imagen: 'public/Imagenes20recetas/Perinal al caldero al estilo boricua.jpeg',
      intro: 'Pernil en pedazos, macerado, sellado en caldero y cocido lento con viandas y caldo. Se deshace solo. Sirves con arroz, tostones, tacos… lo que tengas.',
      tiempo: '~3 h (+ 2 h macerado)',
      porciones: '10+',
      dificultad: 'Media–Alta',
      ingredientes: [
        'Pernil o pierna de cerdo',
        '— Condimento (por cada 3 lbs de carne) —',
        '1/2 cucharada de sofrito',
        '1/2 cucharadita de orégano',
        '1 cucharadita de aceite de oliva',
        '1 diente de ajo',
        '1 cucharadita de sal',
        '1/2 cucharadita de pimienta negra',
        '— Por pernil —',
        '1 cebolla · 1/4 taza de jugo de naranja (china)',
        '— Para cocinar —',
        '5 zanahorias · 5 ramas de apio (celery)',
        '3 papas · 1 cebolla',
        'Pimientos verdes o de colores · Ajíes dulces',
        '3 dientes de ajo · Recao o culantro · Cilantrillo',
        '3 hojas de laurel',
        '12 oz de caldo de pollo (o hasta cubrir)',
        'Salsa de tomate',
      ],
      instrucciones: [
        'Licúa o procesa los ingredientes del condimento.',
        'Retira el cuero del pernil; lava con limón, lima o jugo de naranja.',
        'Corta en pedazos y añade el condimento; macera 2 horas.',
        'Pica cebollas, zanahorias, apio, papas, recao y cilantrillo; reserva.',
        'Caldero a fuego alto: sella el cerdo por todos los lados.',
        'Añade vegetales con un poco de caldo para levantar el fondo del caldero.',
        'Integra el cerdo; añade más caldo hasta cubrir la carne.',
        'Rectifica sal y tapa; cocina a fuego medio 2–3 horas.',
        'A la hora y media destapa para que reduzca un poco el líquido.',
        'El pernil se deshace solo cuando está listo.',
      ],
      notas: 'Muy versátil: sirve con arroz con tocino, tostones, nachos o tacos. ¡Esto es bello!',
    },
    {
      nombre: 'Coquito de Café',
      imagen: 'public/Imagenes20recetas/Coquito de cafe.jpeg',
      intro: 'Crema de coco, leches, ron, licor de café y expreso batidos. Frío de un día para otro y lo sirves con canela. Sin alcohol también sabe.',
      tiempo: '15 min + 3–5 h en nevera (ideal overnight)',
      porciones: '~10–12 copas',
      dificultad: 'Fácil',
      ingredientes: [
        '1 lata crema de coco 15 oz',
        '1 lata leche condensada 13 oz',
        '1 lata leche evaporada 12.5 oz',
        '1 lata leche de coco',
        '8 oz licor de café',
        '8 oz ron',
        '8 oz café expreso',
        '2 cucharaditas de vainilla',
        '1 cucharadita de canela',
      ],
      instrucciones: [
        'En licuadora: crema de coco, todas las leches, licor de café, ron y café expreso.',
        'Mezcla ~5 minutos hasta integrar bien.',
        'Vierte a botella y refrigera mínimo 3–5 horas; mejor de un día para otro.',
        'Sirve en tu vaso preferido con un poco de canela encima.',
      ],
      notas: 'En familia y con amigos. Sin alcohol queda igual de sabroso. ¡Esto es bello!',
    },
    {
      nombre: 'Chili con Carne',
      imagen: 'public/Imagenes20recetas/chilli con carne.jpeg',
      intro: 'Carne molida escurrida, especias, tomate en cubos, habichuelas y caldo. Al final queso rallado y cilantro. Cerveza fría y mesa llena.',
      tiempo: '~35 min',
      porciones: '8',
      dificultad: 'Media',
      ingredientes: [
        '2 lbs carne molida de res',
        'Cebolla y pimientos de colores',
        '1/2 taza de jalapeños',
        '30 oz diced tomatoes',
        '2 cucharadas de sal',
        '1 cucharadita de comino',
        '1 cucharadita de orégano',
        '1 cucharada de ajo molido',
        '1 cucharada de pimienta',
        '2 latas habichuelas rojas',
        '2 tazas caldo de res',
        'Queso rallado al gusto',
        'Cilantrillo fresco o seco',
        '1/2 sobre Original Seasoning Chili Mix',
      ],
      instrucciones: [
        'Cocina la carne a fuego medio hasta que suelte la grasa; cuela.',
        'Condimenta: sal, pimienta, ajo molido, orégano, comino y mix de chili.',
        'Añade diced tomatoes, jalapeños, habichuelas, cebolla y pimientos.',
        'Mezcla todo bien y cocina ~5 minutos.',
        'Añade caldo de res y cocina a fuego medio ~10 minutos.',
        'Incorpora ~2 tazas de queso rallado y cilantrillo fresco.',
      ],
      notas: 'A disfrutar en familia y buenas amistades con una cerveza local bien fría. ¡Esto es bello!',
    },
    {
      nombre: 'Mongolian Beef',
      imagen: 'public/Imagenes20recetas/mongolian beef.jpeg',
      intro: 'Flank steak fino con baking soda y maicena para textura, luego sartén fuerte con ajo, cebolla y salsa soya. En media hora tienes cena con arroz blanco.',
      tiempo: '~30 min',
      porciones: '4',
      dificultad: 'Media',
      ingredientes: [
        '1.5 lbs flank steak (tiras finas ~2 pulgadas)',
        '3 cucharaditas aceite de oliva',
        '1/2 cucharadita sal',
        '1 cucharada pimienta',
        '1 cucharada paprika',
        '1 cucharada baking soda',
        '2 cucharaditas maicena',
        '1 cucharadita agua',
        '— Adicionales —',
        '5–6 dientes de ajo',
        '1 cebolla grande en pedazos',
        '10 cebollines',
        '1/3 taza salsa soya',
        '1 cucharadita azúcar',
        'Pimienta extra (opcional)',
      ],
      instrucciones: [
        'En un envase mezcla el flank steak con todos los primeros ingredientes (aceite, sal, pimienta, paprika, baking soda, maicena y agua).',
        'Cebolla en cubos grandes.',
        'Cebollín: parte blanca ~1/4 pulgada; parte verde ~1 pulgada.',
        'Sartén con aceite a fuego medio-alto: cocina la carne hasta dorar; reserva.',
        'Mismo sartén: aceite, ajo rallado, cebolla y parte blanca del cebollín; ~5 min.',
        'Vuelve la carne y añade la parte verde del cebollín; 3–4 min.',
        'Añade azúcar y salsa soya; pimienta extra opcional.',
        'Mezcla bien, apaga el fuego; sirve a los 3 minutos (en el video con arroz blanco).',
      ],
      notas: 'Pocos ingredientes, muy rica y en 30 minutos. ¡Esto es bello!',
    },
    {
      nombre: 'Bolitas de Queso Rellenas de Guayaba',
      imagen: 'public/Imagenes20recetas/Bolitas de Guayaba.jpeg',
      intro: 'Mozzarella, maicena y huevo hacen la masa; metes guayaba adentro, frío un rato y fríes con paciencia o air fryer. Parmesano arriba y salsa al gusto.',
      tiempo: '35 min (incluye frío y cocción)',
      porciones: '8–12 bolitas',
      dificultad: 'Fácil',
      ingredientes: [
        '300 g queso mozzarella rallado',
        '3 cucharadas maicena',
        '1 huevo',
        'Pasta de guayaba',
      ],
      instrucciones: [
        'En un envase mezcla mozzarella, maicena y huevo hasta masa compacta; amasa bien.',
        'Forma bolitas del tamaño que quieras.',
        'Corta la pasta de guayaba en cubitos pequeños.',
        'Haz un hueco en cada bolita, rellena con guayaba y cierra bien.',
        'Refrigerador ~10 minutos.',
        'Fríe a fuego medio-bajo unos minutos por lado (para que no se quemen por fuera y queden crudas por dentro).',
        'Alternativa: air fryer a 400 °F ~10 minutos.',
        'Al sacar, añade queso parmesano rallado y sirve con tu salsa favorita.',
      ],
      notas: 'Asegúrate de usar queso de buena calidad. Picadera fácil y muy sabrosa. ¡Esto es bello!',
    },
  ],
};
